name: ci

on:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
	  - 
        name: Login DockerHub
        run: echo "${{ secrets.DockerHubPwd }}" | docker login -u "${{ secrets.DockerHubUname }}" --password-stdin
      -
        name: Run Buildx
        run: |
          docker buildx build --push \
          --tag hvalev/onedrive-docker-arm64:latest \
          --platform linux/arm64 .
      - 
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2.1.0
        env:
           DOCKERHUB_USERNAME: ${{ secrets.DockerHubUname }}
           DOCKERHUB_PASSWORD: ${{ secrets.DockerHubPwd }}
           DOCKERHUB_REPOSITORY: hvalev/onedrive-arm64
